http:
  port: ":8080"
  timeout: "15s"
  shutdown_timeout: '30s'
  read_timeout: '15s'
  write_timeout: '60s'

db:
  host: "trello-db"
  port: "5432"
  db_name: "postgres"
  username: "postgres"
  password: "JASIK_2004"